"""Chinese detection, phrase extraction/grouping, dictionary and replacement."""

from .detector import (
    LocatedSegment,
    Segment,
    chinese_segments,
    extract_located_segments,
    han_count,
    han_ratio,
    has_han,
    is_han,
    split_segments,
)
from .dictionary import (
    SOURCE_AI,
    SOURCE_DICTIONARY,
    SOURCE_GLOSS,
    SOURCE_LABELS,
    SOURCE_MANUAL,
    SOURCE_NONE,
    Dictionary,
    DictionaryEntry,
    get_dictionary,
    resolve_translation,
)
from .grouping import PhraseGroup, GroupingResult, filter_groups, group_segments
from .replacer import (
    ReplacementEntry,
    ReplacementReport,
    order_phrases_longest_first,
    replace_chapter_texts,
    replace_phrases,
)
from .master_dictionary import (
    DictionaryHealth,
    ExactMatch,
    MasterDictionary,
    MasterDictionaryError,
    MasterSuggestion,
)
from .review import (
    ChineseReviewSession,
    ReviewAction,
    ReviewFragment,
    ReviewSentence,
    ReviewStatus,
    split_lossless_sentences,
)

__all__ = [
    "LocatedSegment",
    "Segment",
    "chinese_segments",
    "extract_located_segments",
    "han_count",
    "han_ratio",
    "has_han",
    "is_han",
    "split_segments",
    "SOURCE_AI",
    "SOURCE_DICTIONARY",
    "SOURCE_GLOSS",
    "SOURCE_LABELS",
    "SOURCE_MANUAL",
    "SOURCE_NONE",
    "Dictionary",
    "DictionaryEntry",
    "get_dictionary",
    "resolve_translation",
    "PhraseGroup",
    "GroupingResult",
    "filter_groups",
    "group_segments",
    "ReplacementEntry",
    "ReplacementReport",
    "order_phrases_longest_first",
    "replace_chapter_texts",
    "replace_phrases",
    "DictionaryHealth",
    "ExactMatch",
    "MasterDictionary",
    "MasterDictionaryError",
    "MasterSuggestion",
    "ChineseReviewSession",
    "ReviewAction",
    "ReviewFragment",
    "ReviewSentence",
    "ReviewStatus",
    "split_lossless_sentences",
]
